### ISSUE TITLE
Firefox/Mozilla bug with Google Colab

### ISSUE THREAD

**Issue by arpanda** [GMOD/jbrowse-jupyter#73]
I am not sure it's possible to use the bigwig files at google colab's local directory. RangeRequest feature probably needed to make it work. 

I did the following to enable the rangeRequest features as per my understanding of the documentation.
``` python
# install and import
!pip install jbrowse-jupyter
from jbrowse_jupyter import launch, create, serve
```

then created a python script (server.py) to run the server on background

``` server.py
import os
from jbrowse_jupyter import launch, create, serve

def server_run(port=8080):
    
    # Enter a host
    HOST = "localhost"
    
    DIRECTORY = os.getcwd()
    # Enter the path to your local data
    serve(DIRECTORY, port=port, host=HOST)

if __name__ == '__main__':
    port = 8082
    server_run(port)
```
than ran using the followings

``` python
import subprocess
subprocess.Popen(["python3", "server.py"])
```

The above code allows one to get a small content from file. I tested it using the following code and it works.
``` python
import requests

url="http://127.0.0.1:8082/sample_data/anscombe.json"
headers = {"Range": "bytes=5-10"}
r = requests.get(url, headers=headers)
print(r.text)
```
 
But when I am trying to load a bigwig file, it's giving an error. 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/21196859/209743010-bbe52e3f-e7c3-4791-af01-fa8c01743f69.png">

**Comment by teresam856** [comment]
@arpanda Where are these commands being ran ```import subprocess
subprocess.Popen(["python3", "server.py"])```? Could you share what command was used to add the track or additional steps that were taken to configure the track? 


The server provided by JBrowse has range request enabled. It is possible to view bw files with the server provided by JBrowse. Here is a screenshot of a bw file that i have in my local directory and have served using the JBrowse dev server and rendered in colab 
<img width="1344" alt="Screen Shot 2022-12-27 at 6 05 17 PM" src="https://user-images.githubusercontent.com/45598764/209746184-066bc0ce-739e-4a0a-b3bc-b9b5748e5893.png">

**Comment by teresam856** [comment]
@arpanda I just replicated your steps with your script and your command, and I was able to get it to work with subprocess. 

Any chance you have cookies blocked? If so you may need to enable cookies like this https://stackoverflow.com/questions/53581023/google-colab-file-download-failed-to-fetch-error/53582239#53582239

**Comment by arpanda** [comment]
That's great. But I am still getting similar errors. 
Here is the code that I used to create tracks.

```python
assembly_data = "https://jbrowse.org/genomes/CHM13/fasta/chm13v2.0.fa.gz"

ref_name_aliases = {
    "adapter": {
        "type": "RefNameAliasAdapter",
        "location": {"uri": "https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.chromAlias.txt"},
    },
}
chm13 = create('LGV')

chm13.set_assembly(assembly_data, aliases=["chm13v2"], refname_aliases=ref_name_aliases)
chm13.set_location("chr10:100..350")

# add a track
track_data = "https://jbrowse.org/genomes/CHM13/gff/chm13v2.0.gff.gz"
chm13.add_track(track_data, name="test-demo", track_id="test-track")

track_data="http://127.0.0.1:8082/his_rd_p_10000.bw"


chm13.add_track(track_data, track_id="bw1")
chm13.set_default_session(['bw'], False)
new_conf = chm13.get_config()
launch(new_conf, port=3013, height=400)
```

Here is the link of my colab . https://colab.research.google.com/drive/15swbptXiCOoOAxZGnfb0Ve_urQbZ71RO?usp=sharing 

I am using Mozilla and don't think there is any cookie block enabled.

**Comment by teresam856** [comment]
@arpanda  is your his_rd_p_10000.bw in the same place where your serve.py gets created? Your fourth cell should output serve.py and his_rd_p_10000.bw under the directory listing. I ran your notebook and the only thing that I changed was the bw file since I do not have access to yours, and I uploaded it to the same directory where the serve.py exists. It ran fine for me. There is also a typo in your code ```chm13.add_track(track_data, track_id="bw1")
chm13.set_default_session(['bw'], False)``` where bw1 and bw should be the same but I am assuming it was fixed since it does not exist in your shared colab notebook. Another thing that you can do to get additional info, is to change launch(new_conf, port=3013, height=400, mode="external") then you will able to click the link and inspect or look at the console for more error messages.

**Comment by arpanda** [comment]
The path for `his_rd_p_10000.bw` is in the same place where `server.py` gets created and I also fixed the track_id. The only difference is with the bigwig file. I m not sure what's going on and still facing the issue. 

Maybe sharing the bigwig file helps. but GitHub don't support bw file sharing directly. So I zipped it.
[his_rd_p_10000.bw.zip](https://github.com/GMOD/jbrowse-jupyter/files/10312222/his_rd_p_10000.bw.zip)

**Comment by teresam856** [comment]
@arpanda Have you tried running this on Chrome out of curiosity? I am attempting to debug, and it seems like it could be an issue with mixed content on Mozilla  firefox. Before jumping into that conclusion, I wanted to make sure it also did not run in Chrome.

**Comment by teresam856** [comment]
@arpanda Just added your file 
<img width="1436" alt="Screen Shot 2022-12-27 at 9 20 43 PM" src="https://user-images.githubusercontent.com/45598764/209761770-8a2d493c-c466-465b-bffa-c5ce7331ecad.png">

**Comment by arpanda** [comment]
I tried with Chrome too but still facing the same issue. The error message is slightly different.

### Chrome output
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/21196859/209832091-0414835f-6f87-44f5-9f96-b1ed5cab8521.png">
 
### Firefox Mozila output

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/21196859/209832201-6f7c98b7-a67e-43e5-af79-8d653d0ac9be.png">

Note I enabled the third party cookies for chrome too. 
It's probably something with system setting as you'r able to run the same google colab file with same input data.

**Comment by teresam856** [comment]
@arpanda 
Do you have any blocking extensions on chrome? This is how my chrome is set up
<img width="1030" alt="Screen Shot 2022-12-28 at 1 38 28 PM" src="https://user-images.githubusercontent.com/45598764/209874983-1ec8e5ac-45ed-4795-bc8e-3686819b87da.png">

**Comment by cmdcolin** [comment]
maybe close for now.... let me know if there are any updates @arpanda
